### PR TITLE
Move mod contents to shared to sync server and clients script values

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
This move has virtually no impact on the player. What it does do is sync the server's script values to match clients as the code is now ran on both.

Alternative approach would be to call itemTweaker's stuff through a client to server command - but this would be a bit extra when you could just take advantage of the shared folder.

Note: 
"Deadened files" (as I call them) is using an empty file to overwrite other files - rather than deleting them. Deleting files entirely will cause problems as Steam uses a file manifest to update files. It does not remove files - mostly because there is no file to compare to. As such the deleted files from prior versions of the mod will sit there until the user goes to delete it.

With this update there would be no errors/issues but it would cause problems if you ever change any values - users would report that older values are still present.

Also, simply copying the files into server or shared to match clients would make updating the mod super tedious I imagine.

### CODE REVIEW

**Comment by ChobitsCrazy** [comment]
So we need to move all the files to shared?

**Comment by ChuckTheSheep** [comment]
This is what I believe is the easiest solution.

Alternatives:
1. Making a copy of the whole mod in server - cons: To maintain the mod going forward you'd have to make copies of everything and move it over.
2. Make a client-to-server command to update the server of client's script changes. (This is what I originally implemented in my mod as a workaround.)

I would say in a months time or so you can remove the "deadened" files - but they pose no issue just existing.

**Comment by ChuckTheSheep** [comment]
Getting merge errors due to the most recent changes - should I rebase and redo it?

**Comment by ChuckTheSheep** [comment]
pulled your changes to my branch

**Comment by ChobitsCrazy** [comment]
Still have more changes coming before I push the next update out. So I will consider the options before the next release.

**Comment by ChuckTheSheep** [comment]
Ok, let me know when I can update this accordingly.

**Comment by Franisz** [comment]
Moving files from client to shared is certainly fine, but:
> "Deadened files" (as I call them) is using an empty file to overwrite other files - rather than deleting them. Deleting files entirely will cause problems as Steam uses a file manifest to update files. It does not remove files - mostly because there is no file to compare to. As such the deleted files from prior versions of the mod will sit there until the user goes to delete it.

I never heard about steam workshop having such issue. Steam manifest file includes among the others the exact size of each mod. 
I made quick test by adding new file to a mod -> updating to steam workshop -> on update file gets properly added to both `\SteamLibrary\steamapps\workshop\...` and `\ProjectZomboid\steamapps\workshop\...` -> delete that file, update mod on workshop -> on update file gets properly deleted from both locations.

Am I missing something? Is this issue mentioned anywhere?

**Comment by ChuckTheSheep** [comment]
I've had users report files that should have been removed not being removed on updates. Re-verifying the cache/resubscribing does remove files afaik.

**Comment by Chuckleberry-Finn** [comment]
I re-implemented my workaround for this issue.

**Pull request closed without merging**
