### PR TITLE
LeGourmetRevolution support

### PR DESCRIPTION
**Pull request by FanghanHu**
Thank you for the time and effort on such a useful mod, here is some code to add support for **_Snake's Modpack - Le Gourmet Revolution_**
Please let me know if there is any problem.

### CODE REVIEW

**Comment by GaistH** [comment]
Would you mind putting this out as an add-on patch pending pull integration?  It's a fantastic job covering a lot of content!

**Comment by FanghanHu** [comment]
Sorry I have no idea how to do that.

Fanghan Hu

**Comment by FanghanHu** [comment]
I've only done that for my personal use, I'm not interested in publishing a
separate mod, so if you can put a mod together or just include those
changes in your mod's compatibility section, that'd be great.

**Comment by GaistH** [comment]
Alright, I've put it up on the workshop as a patch pending the pull request being implemented and listed full credit to you:  https://steamcommunity.com/sharedfiles/filedetails/?id=2868734860

Should be working fine, let me know if there are any issues though -- and cheers on getting things sorted!

**Comment by FanghanHu** [comment]
Cheers!

Fanghan Hu

**Comment by ChobitsCrazy** [comment]
Gonna be doing an update soon for this.

**Pull request merged**
