### PR TITLE
Add/Update

### PR DESCRIPTION
**Pull request by NCrawler**

### CODE REVIEW

**Comment by NCrawler** [comment]
That MoreMaps_Items.lua should not be in this one.  Mistake on my part I guess.

**Comment by ChobitsCrazy** [comment]
Yeah I'll end up taking it out if possible otherwise will send it back to remove since it's a dupe.

**Review by ChobitsCrazy — CHANGES_REQUESTED** [review]
Yeah doesn't want to let me change it. I'll send it back and you can remove the More Maps edits since they are dupes.

**Comment by ChobitsCrazy** [comment]
Nvm I went ahead and merged since I could change it.

**Pull request merged**
