### PR TITLE
New updates

### PR DESCRIPTION
**Pull request by NCrawler**

### CODE REVIEW

**Comment by NCrawler** [comment]
Disregard that Sharks_Items.lua update.  Forgot that you renamed the file.  Guess I'll need to delete my fork and create it again to get back in sync.

**Comment by NCrawler** [comment]
Had to update the Shark-cyts_Items file so had to download from the original project.  Added the FJ75 vehicle at the bottom of the file.

**Comment by ChobitsCrazy** [comment]
Can you do a new PR for these changes, it's locked on the file edit and will not let me pick which commits to take.

**Comment by NCrawler** [comment]
You might have to delete this entire request first.  I think I should be able to recreate it then

**Pull request closed without merging**
